[build]
  functions = "functions"
  command = "npx puppeteer browsers install chrome"

[[redirects]]
from = "/*"
to = "/.netlify/functions/server"
status = 200


[context.production.environment]
  PUPPETEER_EXECUTABLE_PATH = "/opt/buildhome/.cache/puppeteer/chrome/linux-127.0.6533.119/chrome-linux64/chrome"


[[plugins]]
  package = "netlify-plugin-chromium"
  [plugins.inputs]
    packageManager = "npm"
    setChromePathInEnv = true
    failBuildOnError = true