[build]
  functions = "functions"
  command = "npx puppeteer browsers install chrome"
  publish = "public"

[[redirects]]
from = "/*"
to = "/.netlify/functions/server"
status = 200


[[plugins]]
  package = "netlify-plugin-chromium"
  [plugins.inputs]
    packageManager = "npm"
    setChromePathInEnv = true
    failBuildOnError = true