[build]
functions = "functions"

[[redirects]]
from = "/*"
to = "/.netlify/functions/server"
status = 200


[plugins]
  [[plugins]]
    package = "netlify-plugin-chromium"
    [plugins.inputs]
      packageManager = "npm"
      setChromePathInEnv = false
      failBuildOnError = true